<?php

/**
 * @file
 * Contains wvu_online_exposed_filter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wvu_online_exposed_filter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wvu_online_exposed_filter module.
    case 'help.page.wvu_online_exposed_filter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add exposed filter by title') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function wvu_online_exposed_filter_theme() {
  return [
    'wvu_online_exposed_filter' => [
      'render element' => 'children',
    ],
  ];
}
